[tool.commitizen]
name = "cz_conventional_commits"

[tool.commitizen.bump]
commit_message = "chore: bump version to {version}"
version_file = "pyproject.toml"  # Ensure this points to your version file
